# Generated by Django 3.2.4 on 2021-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='form_email',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
