# Generated by Django 3.2.4 on 2021-06-17 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_formdata_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='form_data',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=2000),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date created'),
        ),
    ]
