# Generated by Django 3.2.4 on 2021-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_formdata_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='api_key',
            field=models.CharField(max_length=50),
        ),
    ]
